In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data.csv")

In [3]:
df

            Date   Retailer                  Company  Margin   Amount
0      7/14/2019       Cash    AnchorVolt Industries   74.17   301.59
1      7/14/2019       Cash    AnchorVolt Industries   48.34   179.81
2      7/14/2019       Cash  HavellCore Technologies   15.72    63.00
3      7/14/2019       Cash      BharatElectra Works  123.21  3178.20
4      7/14/2019       Cash      BharatElectra Works   69.54  2304.18
...          ...        ...                      ...     ...      ...
16769  7/14/2019  SparkWave    AnchorVolt Industries  170.66   949.40
16770  7/14/2019  SparkWave    AnchorVolt Industries  143.12  1702.96
16771  7/14/2019  SparkWave    AnchorVolt Industries  260.72  2835.64
16772  7/14/2019  SparkWave  ElectroSaar Fabricators  -26.32   568.00
16773  7/14/2019  SparkWave  ElectroSaar Fabricators  101.00   624.00

[16774 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16774 entries, 0 to 16773
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      16774 non-null  object
 1   Retailer  16774 non-null  object
 2   Company   16774 non-null  object
 3   Margin    16774 non-null  float64
 4   Amount    16774 non-null  float64
dtypes: float64(2), object(3)
memory usage: 655.4+ KB

In [5]:
df["Date"] = pd.to_datetime(df["Date"])

In [6]:
df

            Date   Retailer                  Company  Margin   Amount
0     2019-07-14       Cash    AnchorVolt Industries   74.17   301.59
1     2019-07-14       Cash    AnchorVolt Industries   48.34   179.81
2     2019-07-14       Cash  HavellCore Technologies   15.72    63.00
3     2019-07-14       Cash      BharatElectra Works  123.21  3178.20
4     2019-07-14       Cash      BharatElectra Works   69.54  2304.18
...          ...        ...                      ...     ...      ...
16769 2019-07-14  SparkWave    AnchorVolt Industries  170.66   949.40
16770 2019-07-14  SparkWave    AnchorVolt Industries  143.12  1702.96
16771 2019-07-14  SparkWave    AnchorVolt Industries  260.72  2835.64
16772 2019-07-14  SparkWave  ElectroSaar Fabricators  -26.32   568.00
16773 2019-07-14  SparkWave  ElectroSaar Fabricators  101.00   624.00

[16774 rows x 5 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16774 entries, 0 to 16773
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      16774 non-null  datetime64[ns]
 1   Retailer  16774 non-null  object
 2   Company   16774 non-null  object
 3   Margin    16774 non-null  float64
 4   Amount    16774 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 655.4+ KB

In [8]:
df["Year"] = df["Date"].dt.year

In [9]:
df

            Date   Retailer                  Company  Margin   Amount  Year
0     2019-07-14       Cash    AnchorVolt Industries   74.17   301.59  2019
1     2019-07-14       Cash    AnchorVolt Industries   48.34   179.81  2019
2     2019-07-14       Cash  HavellCore Technologies   15.72    63.00  2019
3     2019-07-14       Cash      BharatElectra Works  123.21  3178.20  2019
4     2019-07-14       Cash      BharatElectra Works   69.54  2304.18  2019
...          ...        ...                      ...     ...      ...   ...
16769 2019-07-14  SparkWave    AnchorVolt Industries  170.66   949.40  2019
16770 2019-07-14  SparkWave    AnchorVolt Industries  143.12  1702.96  2019
16771 2019-07-14  SparkWave    AnchorVolt Industries  260.72  2835.64  2019
16772 2019-07-14  SparkWave  ElectroSaar Fabricators  -26.32   568.00  2019
16773 2019-07-14  SparkWave  ElectroSaar Fabricators  101.00   624.00  2019

[16774 rows x 6 columns]

In [10]:
df["Month"] = df["Date"].dt.month

In [11]:
df

,Date,Retailer,Company,Margin,Amount,Year,Month
0,2019-07-14,Cash,AnchorVolt Industries,74.17,301.59,2019,7
1,2019-07-14,Cash,AnchorVolt Industries,48.34,179.81,2019,7
2,2019-07-14,Cash,HavellCore Technologies,15.72,63.00,2019,7
3,2019-07-14,Cash,BharatElectra Works,123.21,3178.20,2019,7
4,2019-07-14,Cash,BharatElectra Works,69.54,2304.18,2019,7
...,...,...,...,...,...,...,...
16769,2019-07-14,SparkWave,AnchorVolt Industries,170.66,949.40,2019,7
16770,2019-07-14,SparkWave,AnchorVolt Industries,143.12,1702.96,2019,7
16771,2019-07-14,SparkWave,AnchorVolt Industries,260.72,2835.64,2019,7
16772,2019-07-14,SparkWave,ElectroSaar Fabricators,-26.32,568.00,2019,7
16773,2019-07-14,SparkWave,ElectroSaar Fabricators,101.00,624.00,2019,7

In [12]:
 df["Day"] = df["Date"].dt.day

In [13]:
df

,Date,Retailer,Company,Margin,Amount,Year,Month,Day
0,2019-07-14,Cash,AnchorVolt Industries,74.17,301.59,2019,7,14
1,2019-07-14,Cash,AnchorVolt Industries,48.34,179.81,2019,7,14
2,2019-07-14,Cash,HavellCore Technologies,15.72,63.00,2019,7,14
3,2019-07-14,Cash,BharatElectra Works,123.21,3178.20,2019,7,14
4,2019-07-14,Cash,BharatElectra Works,69.54,2304.18,2019,7,14
...,...,...,...,...,...,...,...,...
16769,2019-07-14,SparkWave,AnchorVolt Industries,170.66,949.40,2019,7,14
16770,2019-07-14,SparkWave,AnchorVolt Industries,143.12,1702.96,2019,7,14
16771,2019-07-14,SparkWave,AnchorVolt Industries,260.72,2835.64,2019,7,14
16772,2019-07-14,SparkWave,ElectroSaar Fabricators,-26.32,568.00,2019,7,14
16773,2019-07-14,SparkWave,ElectroSaar Fabricators,101.00,624.00,2019,7,14

In [14]:
 month_dict = {4:1,5:2,6:3,7:4,8:5,9:6,10:7,11:8,12:9,1:10,2:11,3:12}

In [15]:
 df["Financial_Month"] = df["Month"].map(month_dict)

In [17]:
df

,Date,Retailer,Company,Margin,Amount,Year,Month,Day,Financial_Month
0,2019-07-14,Cash,AnchorVolt Industries,74.17,301.59,2019,7,14,4
1,2019-07-14,Cash,AnchorVolt Industries,48.34,179.81,2019,7,14,4
2,2019-07-14,Cash,HavellCore Technologies,15.72,63.00,2019,7,14,4
3,2019-07-14,Cash,BharatElectra Works,123.21,3178.20,2019,7,14,4
4,2019-07-14,Cash,BharatElectra Works,69.54,2304.18,2019,7,14,4
...,...,...,...,...,...,...,...,...,...
16769,2019-07-14,SparkWave,AnchorVolt Industries,170.66,949.40,2019,7,14,4
16770,2019-07-14,SparkWave,AnchorVolt Industries,143.12,1702.96,2019,7,14,4
16771,2019-07-14,SparkWave,AnchorVolt Industries,260.72,2835.64,2019,7,14,4
16772,2019-07-14,SparkWave,ElectroSaar Fabricators,-26.32,568.00,2019,7,14,4
16773,2019-07-14,SparkWave,ElectroSaar Fabricators,101.00,624.00,2019,7,14,4

In [22]:
df["Financial_Year"] = df.apply(lambda x: f"{x['Year']} - {x['Year'] + 1}" if x['Month'] >= 4 else f"{x['Year'] - 1} - {x['Year']}", axis=1)

In [26]:
df.tail(30)

,Date,Retailer,Company,Margin,Amount,Year,Month,Day,Financial_Month,Financial_Year
16744,2019-07-12,PulseCraft Depot,Others,20.12,73.60,2019,7,12,4,2019 - 2020
16745,2019-07-12,PulseCraft Depot,Others,51.75,55.40,2019,7,12,4,2019 - 2020
16746,2019-07-12,PulseCraft Depot,VoltIndus Fabrications,257.29,771.30,2019,7,12,4,2019 - 2020
16747,2019-07-12,PulseCraft Depot,BharatElectra Works,122.65,3181.20,2019,7,12,4,2019 - 2020
16748,2019-07-12,PulseCraft Depot,BharatElectra Works,71.96,2306.18,2019,7,12,4,2019 - 2020
16749,2019-07-12,PulseCraft Depot,BharatElectra Works,187.52,7345.36,2019,7,12,4,2019 - 2020
16750,2019-07-12,PulseCraft Depot,SupraVolt Manufacturing,64.95,133.00,2019,7,12,4,2019 - 2020
16751,2019-07-12,PulseCraft Depot,SupraVolt Manufacturing,45.57,84.00,2019,7,12,4,2019 - 2020
16752,2019-07-12,PulseCraft Depot,OrionVolt Systems,65.19,194.12,2019,7,12,4,2019 - 2020
16753,2019-07-12,PulseCraft Depot,OrionVolt Systems,119.54,339.34,2019,7,12,4,2019 - 2020
16754,2019-07-12,PulseCraft Depot,OrionVolt Systems,32.36,110.46,2019,7,12,4,2019 - 2020
16755,2019-07-12,PulseCraft Depot,OrionVolt Systems,34.10,99.64,2019,7,12,4,2019 - 2020
16756,2019-07-12,PulseCraft Depot,OrionVolt Systems,141.96,357.53,2019,7,12,4,2019 - 2020
16757,2019-07-12,PulseCraft Depot,OrionVolt Systems,34.96,123.30,2019,7,12,4,2019 - 2020
16758,2019-07-12,PulseCraft Depot,ElectroSaar Fabricators,126.24,350.00,2019,7,12,4,2019 - 2020
16759,2019-07-12,PulseCraft Depot,AnchorVolt Industries,64.26,150.50,2019,7,12,4,2019 - 2020
16760,2019-07-12,PulseCraft Depot,AnchorVolt Industries,32.17,78.70,2019,7,12,4,2019 - 2020
16761,2019-07-12,PulseCraft Depot,OrionVolt Systems,18.92,13.90,2019,7,12,4,2019 - 2020
16762,2019-07-12,PulseCraft Depot,OrionVolt Systems,31.20,74.40,2019,7,12,4,2019 - 2020
16763,2019-07-12,PulseCraft Depot,OrionVolt Systems,63.15,165.60,2019,7,12,4,2019 - 2020
16764,2019-07-13,ElectroVault,AnchorVolt Industries,207.02,1493.80,2019,7,13,4,2019 - 2020
16765,2019-07-13,PulseCraft Depot,AnchorVolt Industries,38.42,77.55,2019,7,13,4,2019 - 2020
16766,2019-07-13,PulseCraft Depot,OrionVolt Systems,30.94,76.40,2019,7,13,4,2019 - 2020
16767,2019-07-14,SparkWave,AnchorVolt Industries,142.68,1331.96,2019,7,14,4,2019 - 2020
16768,2019-07-14,SparkWave,AnchorVolt Industries,150.11,1927.64,2019,7,14,4,2019 - 2020
16769,2019-07-14,SparkWave,AnchorVolt Industries,170.66,949.40,2019,7,14,4,2019 - 2020
16770,2019-07-14,SparkWave,AnchorVolt Industries,143.12,1702.96,2019,7,14,4,2019 - 2020
16771,2019-07-14,SparkWave,AnchorVolt Industries,260.72,2835.64,2019,7,14,4,2019 - 2020
16772,2019-07-14,SparkWave,ElectroSaar Fabricators,-26.32,568.00,2019,7,14,4,2019 - 2020
16773,2019-07-14,SparkWave,ElectroSaar Fabricators,101.00,624.00,2019,7,14,4,2019 - 2020